window.ITINERARY = [
  {
    "date": "Tue 03 Nov",
    "city": "Tokyo",
    "title": "Flight arrival · Tokyo Haneda (HND) · hotel check-in",
    "base": "Tokyo night 1",
    "summary": "Arrival at 22:30. No sightseeing planned; keep this night only for immigration, transfer and sleep.",
    "start": "22:30",
    "hotelCity": "Tokyo",
    "items": [
      {
        "id": "d1_arrival",
        "name": "Arrive at Tokyo Haneda (HND)",
        "time": "22:30",
        "duration": 60,
        "transit": 0,
        "walk": 0.4,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=80",
        "desc": "Your flight arrives at Haneda at 22:30. Plan time for immigration, luggage and getting oriented.",
        "tip": "Because arrival is late, do not plan dinner or sightseeing. Go straight to the hotel.",
        "transport": "After immigration and luggage, follow signs for Keikyu Line / Tokyo Monorail / taxi. At this hour, check the last train connection to your hotel area. Taxi is the fallback if the train timing is tight."
      },
      {
        "id": "d1_transfer",
        "name": "Haneda → Tokyo hotel",
        "time": "23:30",
        "duration": 45,
        "transit": 45,
        "walk": 0.4,
        "effort": 1,
        "cost": 8,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=80",
        "desc": "Late transfer to your selected Tokyo hotel. The exact route depends on the hotel neighborhood.",
        "tip": "For this arrival time, a hotel with easy Haneda access is valuable: Ginza/Shimbashi/Shinagawa/Tokyo Station are especially practical.",
        "transport": "Keikyu is usually best for Shinagawa/Ginza/Asakusa-side hotels. Tokyo Monorail connects to Hamamatsucho/JR. If trains are no longer convenient, use taxi."
      },
      {
        "id": "d1_checkin",
        "name": "Hotel check-in + sleep",
        "time": "00:15",
        "duration": 30,
        "transit": 0,
        "walk": 0.1,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80",
        "desc": "Check in and sleep. Start the real itinerary the next morning.",
        "tip": "Keep the next day rich but not too early if jet lag hits.",
        "transport": "No transport after check-in."
      }
    ]
  },
  {
    "date": "Wed 04 Nov",
    "city": "Tokyo",
    "title": "Asakusa morning · Meiji · Harajuku · Shibuya",
    "base": "Tokyo night 2",
    "summary": "Recover the missed Asakusa walk, then continue west Tokyo. A full day, but grouped logically.",
    "start": "09:00",
    "items": [
      {
        "id": "d2_asakusa",
        "name": "Senso-ji + Asakusa morning",
        "time": "09:00",
        "duration": 75,
        "transit": 25,
        "walk": 1.2,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1513407030348-c983a97b98d8?auto=format&fit=crop&w=900&q=80",
        "desc": "Moved here because your arrival on Nov 03 is too late. It gives you the classic Tokyo start without forcing it after the flight.",
        "tip": "Go before the main daytime crowd if possible, then move west toward Harajuku/Meiji.",
        "transport": "From your hotel, take metro/JR toward Asakusa Station. After the visit, use Ginza Line / JR connections toward Harajuku or Meiji-jingumae."
      },
      {
        "id": "d2_meiji",
        "name": "Meiji Shrine",
        "time": "08:30",
        "duration": 75,
        "transit": 25,
        "walk": 1.8,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=900&q=80",
        "desc": "Forest walk and shrine architecture, best before the city gets busy.",
        "tip": "Start here because morning light and lower crowds make a big difference.",
        "transport": "JR Yamanote Line to Harajuku Station, or Tokyo Metro to Meiji-jingumae."
      },
      {
        "id": "d2_harajuku",
        "name": "Harajuku side streets + Cat Street",
        "time": "10:00",
        "duration": 90,
        "transit": 5,
        "walk": 2.0,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=900&q=80",
        "desc": "Street photography, shops, fashion and quieter corners beyond Takeshita Street.",
        "tip": "Cat Street is a better walking route than staying in the densest tourist stretch.",
        "transport": "Walk from Meiji Shrine/Harajuku toward Cat Street. No train needed."
      },
      {
        "id": "d2_omotesando",
        "name": "Omotesando architecture walk",
        "time": "11:45",
        "duration": 75,
        "transit": 0,
        "walk": 1.5,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1542931287-023b922fa89b?auto=format&fit=crop&w=900&q=80",
        "desc": "A clean design/architecture corridor with good storefront and street details.",
        "tip": "Good for wide-angle city/architecture shots.",
        "transport": "Continue on foot from Cat Street / Harajuku."
      },
      {
        "id": "d2_nezu_museum",
        "name": "Nezu Museum garden",
        "time": "13:30",
        "duration": 90,
        "transit": 10,
        "walk": 0.8,
        "effort": 1,
        "cost": 10,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional art and garden break near Omotesando. Good if you want a calmer cultural stop.",
        "tip": "Add this if you want a slower indoor/garden moment before Shibuya.",
        "transport": "Walk/taxi from Omotesando. It is nearby and does not break the neighborhood logic."
      },
      {
        "id": "d2_shibuya",
        "name": "Shibuya Crossing + Center Gai area",
        "time": "16:00",
        "duration": 60,
        "transit": 10,
        "walk": 1.0,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=900&q=80",
        "desc": "Essential Tokyo energy and a good transition into evening.",
        "tip": "Use a slower shutter for motion blur at the crossing.",
        "transport": "Tokyo Metro Ginza/Hanzomon/Fukutoshin Line from Omotesando to Shibuya, or walk if you still have energy."
      },
      {
        "id": "d2_shibuya_sky",
        "name": "Shibuya Sky sunset / blue hour",
        "time": "17:00",
        "duration": 90,
        "transit": 0,
        "walk": 0.4,
        "effort": 1,
        "cost": 16,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1542931287-023b922fa89b?auto=format&fit=crop&w=900&q=80",
        "desc": "One of the strongest Tokyo viewpoints and worth booking in advance.",
        "tip": "Book a slot that starts before sunset and stay through blue hour.",
        "transport": "Directly above/near Shibuya Station. No additional transport."
      }
    ]
  },
  {
    "date": "Thu 05 Nov",
    "city": "Tokyo",
    "title": "Ueno · Tokyo National Museum · Yanaka",
    "base": "Tokyo night 3",
    "summary": "Museum + old Tokyo, grouped tightly to reduce transport.",
    "start": "09:15",
    "items": [
      {
        "id": "d3_ueno",
        "name": "Ueno Park morning walk",
        "time": "09:15",
        "duration": 45,
        "transit": 20,
        "walk": 1.2,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1554797589-7241bb691973?auto=format&fit=crop&w=900&q=80",
        "desc": "A gentle start before the museum, with park scenery and temple corners.",
        "tip": "Good low-effort buffer before the main museum block.",
        "transport": "JR/Metro to Ueno Station, then walk through the park toward the museum."
      },
      {
        "id": "d3_tnm",
        "name": "Tokyo National Museum",
        "time": "10:15",
        "duration": 150,
        "transit": 0,
        "walk": 0.8,
        "effort": 2,
        "cost": 6,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1554797589-7241bb691973?auto=format&fit=crop&w=900&q=80",
        "desc": "The most important classic museum for a first Japan trip: art, history, craft and cultural context.",
        "tip": "Do not overpack the morning; this deserves proper time.",
        "transport": "Inside Ueno Park, walk from the station or previous stop."
      },
      {
        "id": "d3_ameyoko",
        "name": "Ameyoko market walk",
        "time": "13:30",
        "duration": 45,
        "transit": 8,
        "walk": 0.8,
        "effort": 2,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional busy market texture near Ueno before the calmer Yanaka route.",
        "tip": "Skip if you feel visually overstimulated after the museum.",
        "transport": "Walk from Ueno Park toward Ueno/Okachimachi."
      },
      {
        "id": "d3_yanaka",
        "name": "Yanaka lanes + cemetery paths",
        "time": "14:45",
        "duration": 120,
        "transit": 12,
        "walk": 2.5,
        "effort": 3,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1505069446780-4ef442b5207f?auto=format&fit=crop&w=900&q=80",
        "desc": "Old Tokyo atmosphere, quieter streets, small temples and excellent photography rhythm.",
        "tip": "Late afternoon light is ideal.",
        "transport": "From Ueno, walk toward Yanaka or take JR to Nippori and start from there."
      },
      {
        "id": "d3_nezu",
        "name": "Nezu Shrine",
        "time": "17:00",
        "duration": 45,
        "transit": 8,
        "walk": 0.8,
        "effort": 2,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional shrine add-on if energy is still good; beautiful vermilion gates.",
        "tip": "Good add-on because it is close to Yanaka.",
        "transport": "Walk from Yanaka if energy is good, or skip and return by metro from Nezu/Nippori."
      }
    ]
  },
  {
    "date": "Fri 06 Nov",
    "city": "Tokyo",
    "title": "Day trip: Kamakura + Enoshima base route",
    "base": "Tokyo night 4",
    "summary": "Scenic coastal temples; optional extras instead of either/or.",
    "start": "08:00",
    "items": [
      {
        "id": "d4_train",
        "name": "Tokyo → Kamakura",
        "time": "08:00",
        "duration": 60,
        "transit": 60,
        "walk": 0.3,
        "effort": 1,
        "cost": 11,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=900&q=80",
        "desc": "JR Yokosuka Line from Tokyo/Shinagawa to Kamakura. Easy and good value.",
        "tip": "Start early to keep the day relaxed.",
        "transport": "JR Yokosuka Line: Tokyo/Shinagawa → Kamakura. If staying west Tokyo, route through Shinjuku/Shonan-Shinjuku Line may work better."
      },
      {
        "id": "d4_hasedera",
        "name": "Hase-dera Temple",
        "time": "09:30",
        "duration": 75,
        "transit": 15,
        "walk": 1.0,
        "effort": 3,
        "cost": 3,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=900&q=80",
        "desc": "Beautiful temple complex with coastal views and gardens.",
        "tip": "A bit of stairs, so do not stack too many high-effort stops afterwards.",
        "transport": "From Kamakura Station, take Enoden to Hase Station, then walk."
      },
      {
        "id": "d4_buddha",
        "name": "Great Buddha of Kamakura",
        "time": "11:00",
        "duration": 45,
        "transit": 8,
        "walk": 0.8,
        "effort": 2,
        "cost": 2,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=900&q=80",
        "desc": "Iconic, quick and close to Hase-dera, so it fits naturally.",
        "tip": "Pairing with Hase avoids unnecessary backtracking.",
        "transport": "Walk from Hase-dera area."
      },
      {
        "id": "d4_tsurugaoka",
        "name": "Tsurugaoka Hachimangu",
        "time": "13:30",
        "duration": 75,
        "transit": 15,
        "walk": 1.5,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=900&q=80",
        "desc": "Main Kamakura shrine with a ceremonial approach and strong sense of place.",
        "tip": "Good after lunch; not too physically demanding.",
        "transport": "Return by Enoden/JR or walk depending on lunch location; keep route central."
      },
      {
        "id": "d4_enoshima",
        "name": "Enoshima sunset add-on",
        "time": "16:00",
        "duration": 120,
        "transit": 35,
        "walk": 2.0,
        "effort": 4,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1570459027562-4a916cc6113f?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional coastal sunset extension. Beautiful, but it makes the day much longer.",
        "tip": "Add only if the weather is clear and you still have energy.",
        "transport": "Take Enoden toward Enoshima, then return to Tokyo via Fujisawa/Ofuna depending on route."
      }
    ]
  },
  {
    "date": "Sat 07 Nov",
    "city": "Tokyo",
    "title": "Contemporary art · Ginza · softer city day",
    "base": "Tokyo night 5",
    "summary": "Lower walking intensity after day trip; art + architecture.",
    "start": "09:30",
    "items": [
      {
        "id": "d5_teamlab",
        "name": "TeamLab Planets or Borderless",
        "time": "09:30",
        "duration": 120,
        "transit": 30,
        "walk": 0.8,
        "effort": 2,
        "cost": 25,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1533158326339-7f3cf2404354?auto=format&fit=crop&w=900&q=80",
        "desc": "Immersive art experience; not traditional, but highly visual and memorable.",
        "tip": "Book in advance and go early.",
        "transport": "Route depends on final TeamLab choice. Use Google Maps day-of because Planets and Borderless are in different areas."
      },
      {
        "id": "d5_ginza",
        "name": "Ginza architecture / design walk",
        "time": "12:30",
        "duration": 90,
        "transit": 20,
        "walk": 1.8,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1542931287-023b922fa89b?auto=format&fit=crop&w=900&q=80",
        "desc": "Department-store facades, design shops and polished Tokyo street photography.",
        "tip": "A visually rich but not physically heavy afternoon.",
        "transport": "Metro/JR toward Ginza/Yurakucho. Exact line depends on TeamLab choice."
      },
      {
        "id": "d5_forum",
        "name": "Tokyo International Forum",
        "time": "14:15",
        "duration": 45,
        "transit": 8,
        "walk": 0.6,
        "effort": 1,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1493514789931-586cb221d7a7?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional architecture stop close to Ginza/Yurakucho.",
        "tip": "Good if you enjoy architectural lines and symmetry.",
        "transport": "Walk from Ginza/Yurakucho."
      },
      {
        "id": "d5_palace",
        "name": "Imperial Palace East Gardens",
        "time": "15:30",
        "duration": 75,
        "transit": 12,
        "walk": 1.5,
        "effort": 2,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1493514789931-586cb221d7a7?auto=format&fit=crop&w=900&q=80",
        "desc": "Calm garden walk; useful if you want nature without crossing the city.",
        "tip": "Keep optional so this day stays restful.",
        "transport": "Walk/taxi from Tokyo Station/Yurakucho area."
      }
    ]
  },
  {
    "date": "Sun 08 Nov",
    "city": "Kyoto",
    "title": "Shinkansen to Kyoto · Fushimi Inari · Gion",
    "base": "Kyoto night 1",
    "summary": "Transfer day with one iconic Kyoto evening route.",
    "start": "08:30",
    "hotelCity": "Kyoto",
    "items": [
      {
        "id": "d6_shinkansen",
        "name": "Tokyo/Shinagawa → Kyoto Shinkansen",
        "time": "08:30",
        "duration": 150,
        "transit": 150,
        "walk": 0.6,
        "effort": 1,
        "cost": 85,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=80",
        "desc": "Take the Tokaido Shinkansen. Reserved ordinary seats are enough.",
        "tip": "No national JR Pass needed for this route.",
        "transport": "Use SmartEX or station machines. Board at Tokyo or Shinagawa, arrive Kyoto Station. Send large luggage ahead if preferred."
      },
      {
        "id": "d6_checkin",
        "name": "Kyoto hotel check-in / luggage drop",
        "time": "11:30",
        "duration": 60,
        "transit": 15,
        "walk": 0.5,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80",
        "desc": "Drop luggage and reset before the afternoon route.",
        "tip": "Best areas: Downtown Kyoto / Karasuma-Oike, Kyoto Station, or Gion-Shijo.",
        "transport": "From Kyoto Station, use subway/taxi depending on hotel location."
      },
      {
        "id": "d6_fushimi",
        "name": "Fushimi Inari",
        "time": "15:00",
        "duration": 120,
        "transit": 20,
        "walk": 2.6,
        "effort": 4,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=900&q=80",
        "desc": "Unmissable. Walk beyond the first gate clusters for better photos and fewer people.",
        "tip": "Because this is high-effort, keep the evening gentle.",
        "transport": "JR Nara Line from Kyoto Station to Inari Station. If staying downtown, use Keihan to Fushimi-Inari Station."
      },
      {
        "id": "d6_gion",
        "name": "Gion + Shirakawa canal evening walk",
        "time": "19:00",
        "duration": 75,
        "transit": 20,
        "walk": 1.2,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=900&q=80",
        "desc": "Atmospheric evening walk with traditional streets and reflections.",
        "tip": "Respect private alleys and avoid intrusive photos of people.",
        "transport": "From Fushimi Inari, Keihan Line to Gion-Shijo is the easiest connection."
      }
    ]
  },
  {
    "date": "Mon 09 Nov",
    "city": "Kyoto",
    "title": "Arashiyama cluster · bamboo · gardens · Kinkaku-ji",
    "base": "Kyoto night 2",
    "summary": "Start early; high scenic value, medium-high walking.",
    "start": "07:30",
    "items": [
      {
        "id": "d7_bamboo",
        "name": "Arashiyama Bamboo Grove",
        "time": "07:30",
        "duration": 60,
        "transit": 25,
        "walk": 1.2,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=900&q=80",
        "desc": "Go early. The grove is famous for a reason but gets crowded quickly.",
        "tip": "Arrive before most tour groups.",
        "transport": "JR Sagano Line from Kyoto Station to Saga-Arashiyama, then walk. From downtown, Hankyu to Arashiyama may be better."
      },
      {
        "id": "d7_okochi",
        "name": "Okochi Sanso Garden",
        "time": "08:45",
        "duration": 75,
        "transit": 5,
        "walk": 1.0,
        "effort": 3,
        "cost": 6,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=900&q=80",
        "desc": "Special-gem garden with views and calmer composition after the bamboo grove.",
        "tip": "Worth the entry fee for photography and atmosphere.",
        "transport": "Walk from the bamboo grove."
      },
      {
        "id": "d7_river",
        "name": "Togetsukyo Bridge + river walk",
        "time": "10:15",
        "duration": 60,
        "transit": 5,
        "walk": 1.4,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80",
        "desc": "Classic Arashiyama river scenery and open views.",
        "tip": "A good visual change after temple/garden density.",
        "transport": "Walk downhill from Okochi Sanso / central Arashiyama."
      },
      {
        "id": "d7_tenryuji",
        "name": "Tenryu-ji Garden",
        "time": "11:30",
        "duration": 60,
        "transit": 8,
        "walk": 0.8,
        "effort": 2,
        "cost": 4,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional garden add-on if you want a more complete Arashiyama morning.",
        "tip": "Add only if not garden-fatigued.",
        "transport": "Walk from Bamboo Grove / Arashiyama central area."
      },
      {
        "id": "d7_kinkaku",
        "name": "Kinkaku-ji",
        "time": "14:30",
        "duration": 60,
        "transit": 35,
        "walk": 0.8,
        "effort": 2,
        "cost": 4,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1624253321171-1be53e12f5f4?auto=format&fit=crop&w=900&q=80",
        "desc": "Touristy but unmissable; the reflection view is iconic.",
        "tip": "Because it is not next door, use taxi/bus to keep the day efficient.",
        "transport": "Taxi is simplest from Arashiyama. Public transport is possible but slower with bus transfers."
      }
    ]
  },
  {
    "date": "Tue 10 Nov",
    "city": "Kyoto",
    "title": "Higashiyama cluster · Kiyomizu · Kennin-ji · rest block",
    "base": "Kyoto night 3",
    "summary": "Classic Kyoto, but paced after previous demanding day.",
    "start": "08:00",
    "items": [
      {
        "id": "d8_kiyomizu",
        "name": "Kiyomizu-dera",
        "time": "08:00",
        "duration": 90,
        "transit": 20,
        "walk": 1.5,
        "effort": 3,
        "cost": 3,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=900&q=80",
        "desc": "Kyoto postcard temple with wooden terrace and city views.",
        "tip": "Go early; the surrounding lanes become packed.",
        "transport": "Taxi early morning is efficient. Otherwise bus to Gojozaka/Kiyomizu-michi, then uphill walk."
      },
      {
        "id": "d8_lanes",
        "name": "Sannenzaka / Ninenzaka lanes",
        "time": "09:45",
        "duration": 90,
        "transit": 0,
        "walk": 1.6,
        "effort": 3,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80",
        "desc": "Historic lanes, shops, tea houses and excellent street photography.",
        "tip": "This is close to Kiyomizu, so it is efficient and natural.",
        "transport": "Walk downhill from Kiyomizu-dera."
      },
      {
        "id": "d8_kodaiji",
        "name": "Yasaka Pagoda / Kodai-ji photo stop",
        "time": "11:30",
        "duration": 45,
        "transit": 5,
        "walk": 0.8,
        "effort": 2,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional nearby visual stop before lunch/rest.",
        "tip": "Good if the day still feels comfortable.",
        "transport": "Walk from Ninenzaka/Sannenzaka."
      },
      {
        "id": "d8_kenninji",
        "name": "Kennin-ji",
        "time": "13:30",
        "duration": 75,
        "transit": 10,
        "walk": 0.7,
        "effort": 1,
        "cost": 4,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=900&q=80",
        "desc": "A calm art/temple experience and a lower-effort counterpoint to the morning.",
        "tip": "This is intentionally easier after Kiyomizu walking.",
        "transport": "Walk/taxi from Higashiyama lanes. It sits close to Gion."
      },
      {
        "id": "d8_pontocho",
        "name": "Pontocho / Kamo River evening stroll",
        "time": "17:30",
        "duration": 60,
        "transit": 10,
        "walk": 1.0,
        "effort": 1,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional light evening walk if you are not tired.",
        "tip": "Keep this optional; the day is already strong.",
        "transport": "Walk from Gion/Kennin-ji area toward Pontocho/Kamo River."
      }
    ]
  },
  {
    "date": "Wed 11 Nov",
    "city": "Nara / Osaka",
    "title": "Nara day trip · continue to Osaka hotel",
    "base": "Osaka night 1",
    "summary": "This fixes the logistics: after Nara, continue to Osaka and sleep near USJ/KIX route.",
    "start": "08:30",
    "hotelCity": "Osaka",
    "items": [
      {
        "id": "d9_checkout",
        "name": "Kyoto checkout / luggage to Osaka",
        "time": "08:30",
        "duration": 30,
        "transit": 20,
        "walk": 0.4,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=80",
        "desc": "Check out and either store luggage at Kyoto Station or forward/bring it toward Osaka after Nara.",
        "tip": "Best: use coin lockers or luggage storage, then continue to Osaka after Nara.",
        "transport": "If carrying luggage, store it at Kyoto Station before heading to Nara. Another option is luggage delivery Kyoto → Osaka hotel."
      },
      {
        "id": "d9_train",
        "name": "Kyoto → Nara",
        "time": "09:00",
        "duration": 50,
        "transit": 50,
        "walk": 0.4,
        "effort": 1,
        "cost": 10,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1579689189009-874f5cac2db5?auto=format&fit=crop&w=900&q=80",
        "desc": "Easy day trip from Kyoto. Start earlier because you will sleep in Osaka tonight.",
        "tip": "Kintetsu is often more convenient for Nara Park; JR works well from Kyoto Station.",
        "transport": "Kintetsu Kyoto Line or JR Nara Line. Choose based on luggage/storage and hotel location."
      },
      {
        "id": "d9_todaiji",
        "name": "Todai-ji",
        "time": "10:30",
        "duration": 90,
        "transit": 15,
        "walk": 1.2,
        "effort": 2,
        "cost": 4,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=900&q=80",
        "desc": "Unmissable scale and one of the most memorable temple experiences.",
        "tip": "Do this before wandering too much around the deer park.",
        "transport": "Walk from Kintetsu Nara Station or bus/taxi from JR Nara Station."
      },
      {
        "id": "d9_park",
        "name": "Nara Park slow walk",
        "time": "12:15",
        "duration": 75,
        "transit": 0,
        "walk": 1.8,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1579689189009-874f5cac2db5?auto=format&fit=crop&w=900&q=80",
        "desc": "Deer, open park scenery and temple approaches.",
        "tip": "Good photography, but keep distance and do not overfeed deer.",
        "transport": "Walk from Todai-ji area."
      },
      {
        "id": "d9_kasuga",
        "name": "Kasuga Taisha approach",
        "time": "14:00",
        "duration": 90,
        "transit": 10,
        "walk": 2.0,
        "effort": 3,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional lantern-lined forest approach; beautiful but adds walking.",
        "tip": "Add only if energy is good; you still need to transfer to Osaka.",
        "transport": "Walk from Nara Park/Todai-ji area."
      },
      {
        "id": "d9_osaka",
        "name": "Nara → Osaka hotel check-in",
        "time": "16:00",
        "duration": 75,
        "transit": 60,
        "walk": 0.7,
        "effort": 1,
        "cost": 8,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "Move to Osaka tonight so USJ day is easier and the final airport day has lower risk.",
        "tip": "Stay near Universal City, Namba, Osaka/Umeda or Tennoji depending on your flight/USJ preference.",
        "transport": "Kintetsu Nara → Osaka-Namba is convenient for Namba hotels. JR Nara → Osaka / Universal City may be better for JR-connected hotels."
      }
    ]
  },
  {
    "date": "Thu 12 Nov",
    "city": "Osaka",
    "title": "Universal Studios Japan",
    "base": "Osaka night 2",
    "summary": "Better logistics: wake up in Osaka, less back-and-forth, easier final airport transfer.",
    "start": "07:15",
    "items": [
      {
        "id": "d10_usj_train",
        "name": "Osaka hotel → Universal City Station",
        "time": "07:15",
        "duration": 35,
        "transit": 35,
        "walk": 0.5,
        "effort": 1,
        "cost": 3,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "Much easier than coming from Kyoto. Arrive before opening if Nintendo/Harry Potter/headliners matter.",
        "tip": "Thursday is also a good weekday choice. Staying in Osaka reduces stress significantly.",
        "transport": "From Osaka/Umeda/Namba: JR lines via Nishikujo to Universal City. From Universal City hotels: walk."
      },
      {
        "id": "d10_usj_entry",
        "name": "USJ rope drop + timed entries",
        "time": "08:00",
        "duration": 540,
        "transit": 0,
        "walk": 8.0,
        "effort": 5,
        "cost": 70,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "Full theme-park day. Prioritize Super Nintendo World timed entry, Harry Potter, Hollywood Dream, shows and seasonal events.",
        "tip": "Use the official USJ app. Consider Express Pass if Super Nintendo World/Mario Kart is essential.",
        "transport": "The park entrance is by Universal City Station. Once inside, use the USJ app for live waits and area entry timing."
      },
      {
        "id": "d10_express",
        "name": "Universal Express Pass buffer",
        "time": "Optional",
        "duration": 0,
        "transit": 0,
        "walk": 0,
        "effort": 0,
        "cost": 85,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional but useful if budget allows and you care about Nintendo/Harry Potter/headliners.",
        "tip": "Prices vary heavily by date and type, so this is a placeholder budget line.",
        "transport": "Buy only through official/authorized channels after choosing the exact date."
      },
      {
        "id": "d10_evening",
        "name": "Return to Osaka hotel / simple dinner",
        "time": "19:30",
        "duration": 45,
        "transit": 20,
        "walk": 0.6,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "Keep the evening simple. You will be tired and flying the next day.",
        "tip": "If staying near Universal City, this is effortless. If staying Namba/Umeda, trains are still much shorter than Kyoto.",
        "transport": "Universal City → Nishikujo → Osaka/Namba route depending on hotel."
      }
    ]
  },
  {
    "date": "Fri 13 Nov",
    "city": "Osaka",
    "title": "Osaka final day · Dotonbori / Umeda · KIX departure 23:10",
    "base": "Flight day",
    "summary": "Your flight leaves KIX at 23:10, so this becomes a real Osaka day before the airport.",
    "start": "10:00",
    "items": [
      {
        "id": "d11_checkout",
        "name": "Hotel checkout + luggage storage",
        "time": "10:00",
        "duration": 45,
        "transit": 0,
        "walk": 0.3,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80",
        "desc": "Check out and leave luggage at the hotel or station lockers. Choose based on hotel area and airport route.",
        "tip": "If staying in Namba, leave luggage near Namba for easy Nankai access to KIX. If staying near Universal City, consider luggage storage at hotel and return before airport transfer.",
        "transport": "No major transport yet. Confirm hotel luggage storage before booking."
      },
      {
        "id": "d11_osaka_castle",
        "name": "Osaka Castle Park",
        "time": "11:15",
        "duration": 90,
        "transit": 30,
        "walk": 1.8,
        "effort": 2,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1590253230532-a67f6bc61c9e?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional classic Osaka photo stop. Best as a park/exterior visit; the interior museum is not essential for this trip.",
        "tip": "Add if you want a more traditional Osaka landmark before the urban afternoon.",
        "transport": "Use JR/metro depending on hotel. From Namba: subway/JR via Morinomiya or Osakajokoen. From Umeda: JR Loop Line."
      },
      {
        "id": "d11_namba",
        "name": "Namba · Shinsaibashi · Dotonbori",
        "time": "14:00",
        "duration": 150,
        "transit": 25,
        "walk": 2.4,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "The best final Osaka atmosphere: canals, neon, signs, arcades, food streets and easy last shopping.",
        "tip": "Good final-day photography and easy to keep flexible.",
        "transport": "Use metro/JR to Namba/Shinsaibashi. If your hotel is in Namba, this is the easiest final-day base."
      },
      {
        "id": "d11_umeda",
        "name": "Umeda Sky Building sunset add-on",
        "time": "17:00",
        "duration": 90,
        "transit": 25,
        "walk": 1.0,
        "effort": 1,
        "cost": 13,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional final viewpoint before going to the airport. Good if the weather is clear.",
        "tip": "Only add if you are not worried about time. Otherwise stay around Namba and head to KIX calmly.",
        "transport": "Metro/JR to Osaka/Umeda, then walk. From there, continue to KIX by JR or return to Namba for Nankai depending on luggage."
      },
      {
        "id": "d11_kix",
        "name": "Transfer to Kansai International Airport (KIX)",
        "time": "19:45",
        "duration": 75,
        "transit": 75,
        "walk": 0.6,
        "effort": 1,
        "cost": 15,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=80",
        "desc": "Your return flight departs KIX at 23:10. Aim to reach the airport around 20:45–21:00.",
        "tip": "Do not cut this close. Leave Osaka around 19:30–20:00 depending on hotel/luggage location.",
        "transport": "From Namba: Nankai Rapi:t or Airport Express to KIX. From Osaka/Umeda: JR airport route. From Universal City: connect via Nishikujo/Osaka or use taxi to a convenient airport train/bus point."
      }
    ]
  }
];
