window.ITINERARY = [
  {
    "date": "Tue 03 Nov",
    "city": "Tokyo",
    "title": "Flight arrival · Tokyo Haneda (HND) · hotel check-in",
    "base": "Tokyo night 1",
    "summary": "Arrival at 22:30. Keep the evening only for immigration, transfer and hotel check-in before four full Tokyo days.",
    "start": "22:30",
    "hotelCity": "Tokyo",
    "items": [
      {
        "id": "d1_arrival",
        "name": "Arrive at Tokyo Haneda (HND)",
        "time": "22:30",
        "duration": 60,
        "transit": 0,
        "walk": 0.4,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=80",
        "desc": "Your flight arrives at Haneda at 22:30. Plan time for immigration, luggage and getting oriented.",
        "tip": "Because arrival is late, do not plan dinner or sightseeing. Go straight to the hotel.",
        "transport": "After immigration and luggage, follow signs for Keikyu Line / Tokyo Monorail / taxi. At this hour, check the last train connection to your hotel area. Taxi is the fallback if the train timing is tight."
      },
      {
        "id": "d1_transfer",
        "name": "Haneda → Tokyo hotel",
        "time": "23:30",
        "duration": 45,
        "transit": 45,
        "walk": 0.4,
        "effort": 1,
        "cost": 8,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=80",
        "desc": "Late transfer to your selected Tokyo hotel. The exact route depends on the hotel neighborhood.",
        "tip": "For this arrival time, a hotel with easy Haneda access is valuable: Ginza/Shimbashi/Shinagawa/Tokyo Station are especially practical.",
        "transport": "Keikyu is usually best for Shinagawa/Ginza/Asakusa-side hotels. Tokyo Monorail connects to Hamamatsucho/JR. If trains are no longer convenient, use taxi."
      },
      {
        "id": "d1_checkin",
        "name": "Hotel check-in + sleep",
        "time": "00:15",
        "duration": 30,
        "transit": 0,
        "walk": 0.1,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80",
        "desc": "Check in and sleep. Start the real itinerary the next morning.",
        "tip": "Keep the next day rich but not too early if jet lag hits.",
        "transport": "No transport after check-in."
      }
    ]
  },
  {
    "date": "Wed 04 Nov",
    "city": "Tokyo",
    "title": "Traditional Tokyo · Imperial district · Akihabara",
    "base": "Tokyo night 2",
    "summary": "Start early at Tsukiji, then move west through gardens, Ginza and the Imperial district before finishing among Akihabara’s neon streets.",
    "start": "08:00",
    "items": [
      {
        "id": "tokyo_04_tsukiji",
        "name": "Tsukiji Outer Market + former Fish Market area",
        "time": "08:00",
        "duration": 90,
        "transit": 0,
        "walk": 1.0,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/tsukiji.jpg",
        "desc": "Breakfast stalls, narrow market lanes and the surviving outer-market atmosphere.",
        "tip": "Arrive before 08:30 for lighter crowds.",
        "transport": "Walk 1 km · about 15 min to Hamarikyu Gardens.",
        "address": "4-16-2 Tsukiji, Chuo City, Tokyo 104-0045",
        "priority": "Don't miss",
        "photoTip": "Photograph the compact food stalls, lanterns and market alleys before they fill up."
      },
      {
        "id": "tokyo_04_hamarikyu",
        "name": "Hamarikyu Gardens",
        "time": "09:45",
        "duration": 90,
        "transit": 0,
        "walk": 1.7,
        "effort": 2,
        "cost": 1.61,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/hamarikyu.jpg",
        "desc": "An Edo-period garden where tidal ponds meet Tokyo’s modern skyline.",
        "tip": "Allow time for the pond circuit and teahouse area.",
        "transport": "Walk 1.7 km · about 25 min to Ginza.",
        "address": "1-1 Hamarikyuteien, Chuo City, Tokyo 104-0046",
        "priority": "Highly recommended",
        "photoTip": "Use the skyscrapers as a background contrast behind the garden ponds."
      },
      {
        "id": "tokyo_04_ginza",
        "name": "Ginza + lunch",
        "time": "11:40",
        "duration": 90,
        "transit": 12,
        "walk": 1.5,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/ginza.jpg",
        "desc": "Architecture, department stores and polished streets along Chuo-dori.",
        "tip": "Follow Ginza Six → Chuo-dori → Ginza 4-chome → Yurakucho.",
        "transport": "Metro to Otemachi · about 12 min · ¥180 / €0.97.",
        "address": "Ginza 4-chome intersection, 4-5 Ginza, Chuo City, Tokyo 104-0061",
        "priority": "Highly recommended",
        "photoTip": "The Ginza 4-chome crossing and department-store façades work well with wide lenses."
      },
      {
        "id": "tokyo_04_palace",
        "name": "Imperial Palace East Gardens + Edo Castle ruins",
        "time": "13:30",
        "duration": 120,
        "transit": 0,
        "walk": 2.0,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/imperial-palace.jpg",
        "desc": "Public gardens, stone walls and remnants of Edo Castle within the Imperial Palace grounds.",
        "tip": "Enter via Otemon and carry little because baggage inspection applies.",
        "transport": "Walk about 2 km through Kitanomaru to Yasukuni Shrine.",
        "address": "1-1 Chiyoda, Chiyoda City, Tokyo 100-8111",
        "priority": "Don't miss",
        "photoTip": "Look for layered compositions using stone walls, bridges and modern office towers."
      },
      {
        "id": "tokyo_04_yasukuni",
        "name": "Yasukuni Shrine grounds",
        "time": "16:00",
        "duration": 45,
        "transit": 15,
        "walk": 0.8,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/yasukuni.jpg",
        "desc": "A large Shinto shrine complex in the imperial district. This stop covers the grounds, not the museum.",
        "tip": "Keep the visit concise to preserve the evening timing.",
        "transport": "Metro to Akasaka-mitsuke · about 15 min · ¥180 / €0.97.",
        "address": "3-1-1 Kudankita, Chiyoda City, Tokyo 102-8246",
        "priority": "Highly recommended",
        "photoTip": "The monumental torii and long central approach are the strongest compositions."
      },
      {
        "id": "tokyo_04_newotani",
        "name": "Hotel New Otani Japanese Garden",
        "time": "17:15",
        "duration": 45,
        "transit": 20,
        "walk": 0.7,
        "effort": 2,
        "cost": 0,
        "core": false,
        "booking": false,
        "photo": "images/tokyo/new-otani-garden.jpg",
        "desc": "A compact historic garden with ponds, bridges and seasonal planting.",
        "tip": "This is the easiest stop to skip if the day runs late.",
        "transport": "Metro to Akihabara · about 20 min · ¥210 / €1.13.",
        "address": "4-1 Kioicho, Chiyoda City, Tokyo 102-8578",
        "priority": "Highly recommended",
        "photoTip": "Use reflections around the pond and frame the waterfall with foliage."
      },
      {
        "id": "tokyo_04_akihabara",
        "name": "Akihabara Electric Town",
        "time": "18:30",
        "duration": 150,
        "transit": 0,
        "walk": 2.0,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/akihabara.jpg",
        "desc": "Neon streets, electronics, arcades, manga shops and an energetic evening atmosphere.",
        "tip": "Save shopping time for the end so it cannot delay earlier timed visits.",
        "transport": "End of route.",
        "address": "Around 1 Sotokanda, Chiyoda City, Tokyo 101-0021",
        "priority": "Don't miss",
        "photoTip": "Blue hour and night are best for layered signs, reflections and moving crowds."
      }
    ]
  },
  {
    "date": "Thu 05 Nov",
    "city": "Tokyo",
    "title": "Asakusa · Skytree · historic eastern Tokyo",
    "base": "Tokyo night 3",
    "summary": "Visit Senso-ji before the main crowds, walk the Sumida River to Skytree, then continue through Ryogoku, two Edo museums, Ueno and Ameyoko.",
    "start": "07:30",
    "items": [
      {
        "id": "tokyo_05_asakusa",
        "name": "Asakusa + Kaminarimon + Nakamise + Senso-ji",
        "time": "07:30",
        "duration": 105,
        "transit": 0,
        "walk": 1.5,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/asakusa.jpg",
        "desc": "Tokyo’s most famous temple district, combining the Kaminarimon gate, Nakamise shopping street and Senso-ji.",
        "tip": "The temple is open early even before every Nakamise shop opens.",
        "transport": "Walk across the river to the Asahi Beer Hall.",
        "address": "2-3-1 Asakusa, Taito City, Tokyo 111-0032",
        "priority": "Don't miss",
        "photoTip": "Photograph Kaminarimon before the tour groups, then use temple gates to frame the pagoda."
      },
      {
        "id": "tokyo_05_asahi",
        "name": "Asahi Beer Hall photo stop",
        "time": "09:15",
        "duration": 15,
        "transit": 0,
        "walk": 1.6,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=85",
        "desc": "A quick architectural stop for Philippe Starck’s distinctive riverside complex.",
        "tip": "Stay on schedule; this is a photo stop rather than a full visit.",
        "transport": "Walk 1.6 km · about 25 min along the Sumida River to Skytree.",
        "address": "1-23-1 Azumabashi, Sumida City, Tokyo 130-8602",
        "priority": "Highly recommended",
        "photoTip": "Shoot from the Asakusa side of the river to include the gold building and Skytree."
      },
      {
        "id": "tokyo_05_skytree",
        "name": "Tokyo Skytree · Tembo Deck",
        "time": "10:00",
        "duration": 90,
        "transit": 15,
        "walk": 0.5,
        "effort": 2,
        "cost": 9.69,
        "core": true,
        "booking": true,
        "photo": "images/tokyo/skytree.jpg",
        "desc": "A 350-metre observation deck with a sweeping view over eastern Tokyo.",
        "tip": "Book online; the Tembo Deck is sufficient unless visibility is exceptional.",
        "transport": "Train to Ryogoku · about 15 min · ¥180 / €0.97.",
        "address": "1-1-2 Oshiage, Sumida City, Tokyo 131-0045",
        "priority": "Don't miss",
        "photoTip": "Use the river bends and dense city grid as leading lines from the windows."
      },
      {
        "id": "tokyo_05_ryogoku",
        "name": "Ryogoku Kokugikan exterior",
        "time": "11:50",
        "duration": 25,
        "transit": 0,
        "walk": 0.7,
        "effort": 2,
        "cost": 0,
        "core": false,
        "booking": false,
        "photo": "images/tokyo/ryogoku-kokugikan.jpg",
        "desc": "Exterior look at Tokyo’s principal sumo arena. There is no Tokyo grand tournament in November.",
        "tip": "Treat this as a short photography and orientation stop.",
        "transport": "Walk about 10 min to the Edo-Tokyo Museum.",
        "address": "1-3-28 Yokoami, Sumida City, Tokyo 130-0015",
        "priority": "Highly recommended",
        "photoTip": "The broad entrance and sumo-themed details are the most distinctive frames."
      },
      {
        "id": "tokyo_05_edotokyo",
        "name": "Edo-Tokyo Museum",
        "time": "12:30",
        "duration": 150,
        "transit": 10,
        "walk": 0.7,
        "effort": 2,
        "cost": 4.31,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/edo-tokyo-museum.jpg",
        "desc": "Large reconstructions and city models explain how Edo developed into modern Tokyo.",
        "tip": "Prioritise the large-scale reconstructions and city models.",
        "transport": "Metro to Kiyosumi-shirakawa · about 10 min · ¥180 / €0.97.",
        "address": "1-4-1 Yokoami, Sumida City, Tokyo 130-0015",
        "priority": "Don't miss",
        "photoTip": "Interior models and reconstructed streets offer strong symmetrical compositions."
      },
      {
        "id": "tokyo_05_fukagawa",
        "name": "Fukagawa Edo Museum",
        "time": "15:20",
        "duration": 70,
        "transit": 20,
        "walk": 0.7,
        "effort": 2,
        "cost": 2.15,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/fukagawa-edo-museum.jpg",
        "desc": "An intimate, atmospheric recreation of a nineteenth-century Fukagawa neighbourhood.",
        "tip": "It complements rather than duplicates the broader Edo-Tokyo Museum.",
        "transport": "Metro to Ueno · about 20 min · ¥220 / €1.18.",
        "address": "1-3-28 Shirakawa, Koto City, Tokyo 135-0021",
        "priority": "Highly recommended",
        "photoTip": "Low-light village interiors look best with steady, wider compositions."
      },
      {
        "id": "tokyo_05_ueno",
        "name": "Ueno Park evening walk",
        "time": "17:00",
        "duration": 45,
        "transit": 0,
        "walk": 1.0,
        "effort": 2,
        "cost": 0,
        "core": false,
        "booking": false,
        "photo": "images/tokyo/ueno-park.jpg",
        "desc": "A relaxed transition through one of Tokyo’s major cultural parks.",
        "tip": "Keep moving toward the southern side of the park and Ameyoko.",
        "transport": "Walk about 10 min to Ameyoko Shopping Street.",
        "address": "Uenokoen, Taito City, Tokyo 110-0007",
        "priority": "Highly recommended",
        "photoTip": "Use the park avenues and temple details rather than trying to cover the whole park."
      },
      {
        "id": "tokyo_05_ameyoko",
        "name": "Ameyoko Shopping Street + dinner",
        "time": "17:45",
        "duration": 90,
        "transit": 0,
        "walk": 1.5,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/ameyoko.jpg",
        "desc": "A lively market street beneath and beside the railway tracks, ideal for browsing and dinner.",
        "tip": "The late-afternoon transition into evening gives the best atmosphere.",
        "transport": "End of route.",
        "address": "6-10 Ueno, Taito City, Tokyo 110-0005",
        "priority": "Highly recommended",
        "photoTip": "Photograph colourful shop signs, food stalls and the railway structure overhead."
      }
    ]
  },
  {
    "date": "Fri 06 Nov",
    "city": "Tokyo",
    "title": "Gotokuji · Harajuku · Shibuya · Shinjuku",
    "base": "Tokyo night 4",
    "summary": "Begin with Gotokuji’s maneki-neko, walk through Meiji Jingu and Cat Street, then combine Shibuya and Shinjuku with two contrasting night viewpoints.",
    "start": "08:30",
    "items": [
      {
        "id": "tokyo_06_gotokuji",
        "name": "Gotokuji Temple",
        "time": "08:30",
        "duration": 60,
        "transit": 35,
        "walk": 1.0,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/gotokuji.jpg",
        "desc": "A quiet temple known for hundreds of maneki-neko lucky-cat figures.",
        "tip": "Arrive early before the cat-figure area becomes crowded.",
        "transport": "Train to Meiji-jingumae / Harajuku · about 35 min · ¥220 / €1.18.",
        "address": "2-24-7 Gotokuji, Setagaya City, Tokyo 154-0021",
        "priority": "Highly recommended",
        "photoTip": "Use a medium focal length to compress the rows of maneki-neko figures."
      },
      {
        "id": "tokyo_06_meiji",
        "name": "Meiji Jingu Shrine",
        "time": "10:10",
        "duration": 90,
        "transit": 0,
        "walk": 2.0,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/meiji-jingu.jpg",
        "desc": "A major Shinto shrine reached through a long forested approach in central Tokyo.",
        "tip": "Allow time for both the forest walk and shrine complex.",
        "transport": "Walk toward Cat Street via Harajuku.",
        "address": "1-1 Yoyogikamizonocho, Shibuya City, Tokyo 151-8557",
        "priority": "Don't miss",
        "photoTip": "The giant torii and long gravel avenues are strongest with people included for scale."
      },
      {
        "id": "tokyo_06_catstreet",
        "name": "Cat Street + lunch",
        "time": "11:45",
        "duration": 90,
        "transit": 0,
        "walk": 1.8,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1200&q=85",
        "desc": "A relaxed pedestrian route of independent shops, cafés, side streets and contemporary storefronts.",
        "tip": "Use this as the walking connection from Harajuku to Shibuya.",
        "transport": "Walk toward Shibuya Station.",
        "address": "Jingumae 4-12 area, Shibuya City, Tokyo 150-0001",
        "priority": "Highly recommended",
        "photoTip": "Look for graphic façades, fashion details and layered street scenes."
      },
      {
        "id": "tokyo_06_hachiko",
        "name": "Hachiko Statue + Shibuya Crossing",
        "time": "13:20",
        "duration": 30,
        "transit": 8,
        "walk": 0.6,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/hachiko-shibuya-crossing.jpg",
        "desc": "A quick visit to the Hachiko statue followed by Tokyo’s best-known pedestrian crossing.",
        "tip": "Cross at street level and use one elevated viewpoint rather than lingering too long.",
        "transport": "JR to Shinjuku · about 8 min · ¥170 / €0.91.",
        "address": "2-1 Dogenzaka, Shibuya City, Tokyo 150-0043",
        "priority": "Don't miss",
        "photoTip": "Try one wide crossing image and one slower-shutter frame from above."
      },
      {
        "id": "tokyo_06_gyoen",
        "name": "Shinjuku Gyoen National Garden",
        "time": "14:20",
        "duration": 100,
        "transit": 0,
        "walk": 2.0,
        "effort": 2,
        "cost": 2.69,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/shinjuku-gyoen.jpg",
        "desc": "Tokyo’s strongest landscaped garden on this itinerary, combining Japanese, English and French styles.",
        "tip": "Enter promptly because winter closing times are earlier.",
        "transport": "Walk about 2 km through Shinjuku to the government district.",
        "address": "11 Naitomachi, Shinjuku City, Tokyo 160-0014",
        "priority": "Don't miss",
        "photoTip": "The greenhouse, skyline-over-garden view and formal avenues provide variety."
      },
      {
        "id": "tokyo_06_tmg",
        "name": "Tokyo Metropolitan Government Building observatory",
        "time": "16:30",
        "duration": 50,
        "transit": 0,
        "walk": 1.5,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/tokyo-metropolitan-view.jpg",
        "desc": "A free panoramic city view from the Shinjuku government district.",
        "tip": "Use this as the sunset/blue-hour panorama before the paid night view later.",
        "transport": "Walk about 20 min to Omoide Yokocho.",
        "address": "2-8-1 Nishishinjuku, Shinjuku City, Tokyo 163-8001",
        "priority": "Highly recommended",
        "photoTip": "On clear days, look west toward Mount Fuji; after sunset, focus on the city grid."
      },
      {
        "id": "tokyo_06_omoide",
        "name": "Omoide Yokocho",
        "time": "17:40",
        "duration": 40,
        "transit": 0,
        "walk": 0.5,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/omoide-yokocho.jpg",
        "desc": "A compact alley network of tiny yakitori restaurants and smoky evening atmosphere.",
        "tip": "A good early-dinner stop, but keep service time in mind.",
        "transport": "Walk about 8 min to Golden Gai.",
        "address": "1-2 Nishishinjuku, Shinjuku City, Tokyo 160-0023",
        "priority": "Highly recommended",
        "photoTip": "Photograph discreetly from the alley entrances and avoid blocking diners."
      },
      {
        "id": "tokyo_06_goldengai",
        "name": "Golden Gai + Kabukicho + Godzilla Road",
        "time": "18:25",
        "duration": 60,
        "transit": 10,
        "walk": 1.4,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/golden-gai-kabukicho.jpg",
        "desc": "Lantern-lit micro-bars followed by Kabukicho’s neon streets and the Godzilla Head.",
        "tip": "Walk Golden Gai first, then continue in one direction through Kabukicho.",
        "transport": "JR back to Shibuya · about 10 min · ¥170 / €0.91.",
        "address": "1-1-6 Kabukicho, Shinjuku City, Tokyo 160-0021",
        "priority": "Highly recommended",
        "photoTip": "Neon reflections and tight alley perspectives are especially effective after rain."
      },
      {
        "id": "tokyo_06_shibuyasky",
        "name": "Shibuya Sky",
        "time": "20:00",
        "duration": 90,
        "transit": 0,
        "walk": 0.5,
        "effort": 2,
        "cost": 18.3,
        "core": true,
        "booking": true,
        "photo": "images/tokyo/shibuya-sky.jpg",
        "desc": "An open-air rooftop observatory above Shibuya Scramble Square.",
        "tip": "Reserve the 20:00 slot in advance and check the rooftop weather policy.",
        "transport": "End of route.",
        "address": "Shibuya Scramble Square, 2-24-12 Shibuya, Tokyo 150-6145",
        "priority": "Don't miss",
        "photoTip": "The west terrace and north corner offer the best skyline layers after dark."
      }
    ]
  },
  {
    "date": "Sat 07 Nov",
    "city": "Tokyo",
    "title": "Nezu · Rikugien · museums · Tokyo Bay",
    "base": "Tokyo night 5",
    "summary": "Use the quiet morning for Nezu and Rikugien, spend midday in the Tokyo National Museum, then finish with contemporary art, Roppongi and Odaiba’s illuminated waterfront.",
    "start": "08:00",
    "items": [
      {
        "id": "tokyo_07_nezu",
        "name": "Nezu Shrine",
        "time": "08:00",
        "duration": 45,
        "transit": 20,
        "walk": 0.8,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/nezu-shrine.jpg",
        "desc": "A historic shrine complex with vermilion structures and a tunnel of small torii gates.",
        "tip": "Arrive before Saturday photography groups.",
        "transport": "Train / metro to Komagome · about 20 min · ¥180–¥220 / €0.97–€1.18.",
        "address": "1-28-9 Nezu, Bunkyo City, Tokyo 113-0031",
        "priority": "Highly recommended",
        "photoTip": "The small torii tunnel and red shrine structures are the strongest visual elements."
      },
      {
        "id": "tokyo_07_rikugien",
        "name": "Rikugien Garden",
        "time": "09:15",
        "duration": 75,
        "transit": 10,
        "walk": 1.2,
        "effort": 2,
        "cost": 1.61,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/rikugien.jpg",
        "desc": "A classic strolling garden built around a large pond and literary landscape scenes.",
        "tip": "Early November is before the heaviest autumn-colour crowds.",
        "transport": "JR to Ueno · about 10 min · ¥170 / €0.91.",
        "address": "6-16-3 Honkomagome, Bunkyo City, Tokyo 113-0021",
        "priority": "Highly recommended",
        "photoTip": "Use pond reflections and curved bridges; longer focal lengths isolate seasonal foliage."
      },
      {
        "id": "tokyo_07_tnm",
        "name": "Tokyo National Museum",
        "time": "11:00",
        "duration": 150,
        "transit": 25,
        "walk": 1.0,
        "effort": 2,
        "cost": 5.38,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/tokyo-national-museum.jpg",
        "desc": "Japan’s most important collection of traditional art, archaeology and cultural objects.",
        "tip": "Prioritise Honkan, the Gallery of Horyuji Treasures and one extra building.",
        "transport": "Metro to Roppongi · about 25 min · ¥220 / €1.18.",
        "address": "13-9 Uenokoen, Taito City, Tokyo 110-8712",
        "priority": "Don't miss",
        "photoTip": "The Honkan architecture and courtyard are as photogenic as many interior galleries."
      },
      {
        "id": "tokyo_07_mori",
        "name": "Mori Art Museum",
        "time": "15:00",
        "duration": 120,
        "transit": 0,
        "walk": 0.8,
        "effort": 2,
        "cost": 13.45,
        "core": true,
        "booking": true,
        "photo": "images/tokyo/mori-art-museum.jpg",
        "desc": "A major contemporary-art museum on the 53rd floor of Roppongi Hills Mori Tower.",
        "tip": "Check the exhibition calendar and possible closure between shows.",
        "transport": "Walk around Roppongi Hills.",
        "address": "Roppongi Hills Mori Tower 53F, 6-10-1 Roppongi, Minato City, Tokyo 106-6150",
        "priority": "Highly recommended",
        "photoTip": "Photography rules vary by exhibition; architectural details around the entrance are reliable."
      },
      {
        "id": "tokyo_07_roppongi",
        "name": "Roppongi neighbourhood walk",
        "time": "17:00",
        "duration": 45,
        "transit": 35,
        "walk": 1.3,
        "effort": 2,
        "cost": 0,
        "core": false,
        "booking": false,
        "photo": "images/tokyo/roppongi.jpg",
        "desc": "A short urban and architectural walk around Roppongi Hills and the crossing.",
        "tip": "Keep this compact so the Tokyo Bay evening remains relaxed.",
        "transport": "Metro + Yurikamome to Odaiba · about 35 min · ¥330–¥430 / €1.78–€2.31.",
        "address": "Roppongi Crossing, 6 Roppongi, Minato City, Tokyo 106-0032",
        "priority": "Highly recommended",
        "photoTip": "Use Mori Tower, public art and elevated walkways for architectural compositions."
      },
      {
        "id": "tokyo_07_odaiba",
        "name": "Odaiba waterfront + Rainbow Bridge views",
        "time": "18:30",
        "duration": 120,
        "transit": 0,
        "walk": 2.0,
        "effort": 2,
        "cost": 0,
        "core": true,
        "booking": false,
        "photo": "images/tokyo/odaiba-rainbow-bridge.jpg",
        "desc": "An evening waterfront walk with the illuminated Rainbow Bridge and central Tokyo skyline.",
        "tip": "View the bridge from the waterfront rather than using time on the pedestrian crossing.",
        "transport": "End of route.",
        "address": "Odaiba Marine Park, 1-4 Daiba, Minato City, Tokyo 135-0091",
        "priority": "Highly recommended",
        "photoTip": "Blue hour is ideal; use foreground rocks or railings to anchor the skyline composition."
      }
    ]
  },
  {
    "date": "Sun 08 Nov",
    "city": "Kyoto",
    "title": "Shinkansen to Kyoto · Fushimi Inari · Gion",
    "base": "Kyoto night 1",
    "summary": "Transfer day with one iconic Kyoto evening route.",
    "start": "08:30",
    "hotelCity": "Kyoto",
    "items": [
      {
        "id": "d6_shinkansen",
        "name": "Tokyo/Shinagawa → Kyoto Shinkansen",
        "time": "08:30",
        "duration": 150,
        "transit": 150,
        "walk": 0.6,
        "effort": 1,
        "cost": 85,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=80",
        "desc": "Take the Tokaido Shinkansen. Reserved ordinary seats are enough.",
        "tip": "No national JR Pass needed for this route.",
        "transport": "Use SmartEX or station machines. Board at Tokyo or Shinagawa, arrive Kyoto Station. Send large luggage ahead if preferred."
      },
      {
        "id": "d6_checkin",
        "name": "Kyoto hotel check-in / luggage drop",
        "time": "11:30",
        "duration": 60,
        "transit": 15,
        "walk": 0.5,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80",
        "desc": "Drop luggage and reset before the afternoon route.",
        "tip": "Best areas: Downtown Kyoto / Karasuma-Oike, Kyoto Station, or Gion-Shijo.",
        "transport": "From Kyoto Station, use subway/taxi depending on hotel location."
      },
      {
        "id": "d6_fushimi",
        "name": "Fushimi Inari",
        "time": "15:00",
        "duration": 120,
        "transit": 20,
        "walk": 2.6,
        "effort": 4,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=900&q=80",
        "desc": "Unmissable. Walk beyond the first gate clusters for better photos and fewer people.",
        "tip": "Because this is high-effort, keep the evening gentle.",
        "transport": "JR Nara Line from Kyoto Station to Inari Station. If staying downtown, use Keihan to Fushimi-Inari Station."
      },
      {
        "id": "d6_gion",
        "name": "Gion + Shirakawa canal evening walk",
        "time": "19:00",
        "duration": 75,
        "transit": 20,
        "walk": 1.2,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=900&q=80",
        "desc": "Atmospheric evening walk with traditional streets and reflections.",
        "tip": "Respect private alleys and avoid intrusive photos of people.",
        "transport": "From Fushimi Inari, Keihan Line to Gion-Shijo is the easiest connection."
      }
    ]
  },
  {
    "date": "Mon 09 Nov",
    "city": "Kyoto",
    "title": "Arashiyama cluster · bamboo · gardens · Kinkaku-ji",
    "base": "Kyoto night 2",
    "summary": "Start early; high scenic value, medium-high walking.",
    "start": "07:30",
    "items": [
      {
        "id": "d7_bamboo",
        "name": "Arashiyama Bamboo Grove",
        "time": "07:30",
        "duration": 60,
        "transit": 25,
        "walk": 1.2,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=900&q=80",
        "desc": "Go early. The grove is famous for a reason but gets crowded quickly.",
        "tip": "Arrive before most tour groups.",
        "transport": "JR Sagano Line from Kyoto Station to Saga-Arashiyama, then walk. From downtown, Hankyu to Arashiyama may be better."
      },
      {
        "id": "d7_okochi",
        "name": "Okochi Sanso Garden",
        "time": "08:45",
        "duration": 75,
        "transit": 5,
        "walk": 1.0,
        "effort": 3,
        "cost": 6,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=900&q=80",
        "desc": "Special-gem garden with views and calmer composition after the bamboo grove.",
        "tip": "Worth the entry fee for photography and atmosphere.",
        "transport": "Walk from the bamboo grove."
      },
      {
        "id": "d7_river",
        "name": "Togetsukyo Bridge + river walk",
        "time": "10:15",
        "duration": 60,
        "transit": 5,
        "walk": 1.4,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80",
        "desc": "Classic Arashiyama river scenery and open views.",
        "tip": "A good visual change after temple/garden density.",
        "transport": "Walk downhill from Okochi Sanso / central Arashiyama."
      },
      {
        "id": "d7_tenryuji",
        "name": "Tenryu-ji Garden",
        "time": "11:30",
        "duration": 60,
        "transit": 8,
        "walk": 0.8,
        "effort": 2,
        "cost": 4,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional garden add-on if you want a more complete Arashiyama morning.",
        "tip": "Add only if not garden-fatigued.",
        "transport": "Walk from Bamboo Grove / Arashiyama central area."
      },
      {
        "id": "d7_kinkaku",
        "name": "Kinkaku-ji",
        "time": "14:30",
        "duration": 60,
        "transit": 35,
        "walk": 0.8,
        "effort": 2,
        "cost": 4,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1624253321171-1be53e12f5f4?auto=format&fit=crop&w=900&q=80",
        "desc": "Touristy but unmissable; the reflection view is iconic.",
        "tip": "Because it is not next door, use taxi/bus to keep the day efficient.",
        "transport": "Taxi is simplest from Arashiyama. Public transport is possible but slower with bus transfers."
      }
    ]
  },
  {
    "date": "Tue 10 Nov",
    "city": "Kyoto",
    "title": "Higashiyama cluster · Kiyomizu · Kennin-ji · rest block",
    "base": "Kyoto night 3",
    "summary": "Classic Kyoto, but paced after previous demanding day.",
    "start": "08:00",
    "items": [
      {
        "id": "d8_kiyomizu",
        "name": "Kiyomizu-dera",
        "time": "08:00",
        "duration": 90,
        "transit": 20,
        "walk": 1.5,
        "effort": 3,
        "cost": 3,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=900&q=80",
        "desc": "Kyoto postcard temple with wooden terrace and city views.",
        "tip": "Go early; the surrounding lanes become packed.",
        "transport": "Taxi early morning is efficient. Otherwise bus to Gojozaka/Kiyomizu-michi, then uphill walk."
      },
      {
        "id": "d8_lanes",
        "name": "Sannenzaka / Ninenzaka lanes",
        "time": "09:45",
        "duration": 90,
        "transit": 0,
        "walk": 1.6,
        "effort": 3,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80",
        "desc": "Historic lanes, shops, tea houses and excellent street photography.",
        "tip": "This is close to Kiyomizu, so it is efficient and natural.",
        "transport": "Walk downhill from Kiyomizu-dera."
      },
      {
        "id": "d8_kodaiji",
        "name": "Yasaka Pagoda / Kodai-ji photo stop",
        "time": "11:30",
        "duration": 45,
        "transit": 5,
        "walk": 0.8,
        "effort": 2,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional nearby visual stop before lunch/rest.",
        "tip": "Good if the day still feels comfortable.",
        "transport": "Walk from Ninenzaka/Sannenzaka."
      },
      {
        "id": "d8_kenninji",
        "name": "Kennin-ji",
        "time": "13:30",
        "duration": 75,
        "transit": 10,
        "walk": 0.7,
        "effort": 1,
        "cost": 4,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=900&q=80",
        "desc": "A calm art/temple experience and a lower-effort counterpoint to the morning.",
        "tip": "This is intentionally easier after Kiyomizu walking.",
        "transport": "Walk/taxi from Higashiyama lanes. It sits close to Gion."
      },
      {
        "id": "d8_pontocho",
        "name": "Pontocho / Kamo River evening stroll",
        "time": "17:30",
        "duration": 60,
        "transit": 10,
        "walk": 1.0,
        "effort": 1,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional light evening walk if you are not tired.",
        "tip": "Keep this optional; the day is al strong.",
        "transport": "Walk from Gion/Kennin-ji area toward Pontocho/Kamo River."
      }
    ]
  },
  {
    "date": "Wed 11 Nov",
    "city": "Nara / Osaka",
    "title": "Nara day trip · continue to Osaka hotel",
    "base": "Osaka night 1",
    "summary": "This fixes the logistics: after Nara, continue to Osaka and sleep near USJ/KIX route.",
    "start": "08:30",
    "hotelCity": "Osaka",
    "items": [
      {
        "id": "d9_checkout",
        "name": "Kyoto checkout / luggage to Osaka",
        "time": "08:30",
        "duration": 30,
        "transit": 20,
        "walk": 0.4,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=80",
        "desc": "Check out and either store luggage at Kyoto Station or forward/bring it toward Osaka after Nara.",
        "tip": "Best: use coin lockers or luggage storage, then continue to Osaka after Nara.",
        "transport": "If carrying luggage, store it at Kyoto Station before heading to Nara. Another option is luggage delivery Kyoto → Osaka hotel."
      },
      {
        "id": "d9_train",
        "name": "Kyoto → Nara",
        "time": "09:00",
        "duration": 50,
        "transit": 50,
        "walk": 0.4,
        "effort": 1,
        "cost": 10,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1579689189009-874f5cac2db5?auto=format&fit=crop&w=900&q=80",
        "desc": "Easy day trip from Kyoto. Start earlier because you will sleep in Osaka tonight.",
        "tip": "Kintetsu is often more convenient for Nara Park; JR works well from Kyoto Station.",
        "transport": "Kintetsu Kyoto Line or JR Nara Line. Choose based on luggage/storage and hotel location."
      },
      {
        "id": "d9_todaiji",
        "name": "Todai-ji",
        "time": "10:30",
        "duration": 90,
        "transit": 15,
        "walk": 1.2,
        "effort": 2,
        "cost": 4,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=900&q=80",
        "desc": "Unmissable scale and one of the most memorable temple experiences.",
        "tip": "Do this before wandering too much around the deer park.",
        "transport": "Walk from Kintetsu Nara Station or bus/taxi from JR Nara Station."
      },
      {
        "id": "d9_park",
        "name": "Nara Park slow walk",
        "time": "12:15",
        "duration": 75,
        "transit": 0,
        "walk": 1.8,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1579689189009-874f5cac2db5?auto=format&fit=crop&w=900&q=80",
        "desc": "Deer, open park scenery and temple approaches.",
        "tip": "Good photography, but keep distance and do not overfeed deer.",
        "transport": "Walk from Todai-ji area."
      },
      {
        "id": "d9_kasuga",
        "name": "Kasuga Taisha approach",
        "time": "14:00",
        "duration": 90,
        "transit": 10,
        "walk": 2.0,
        "effort": 3,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional lantern-lined forest approach; beautiful but adds walking.",
        "tip": "Add only if energy is good; you still need to transfer to Osaka.",
        "transport": "Walk from Nara Park/Todai-ji area."
      },
      {
        "id": "d9_osaka",
        "name": "Nara → Osaka hotel check-in",
        "time": "16:00",
        "duration": 75,
        "transit": 60,
        "walk": 0.7,
        "effort": 1,
        "cost": 8,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "Move to Osaka tonight so USJ day is easier and the final airport day has lower risk.",
        "tip": "Stay near Universal City, Namba, Osaka/Umeda or Tennoji depending on your flight/USJ preference.",
        "transport": "Kintetsu Nara → Osaka-Namba is convenient for Namba hotels. JR Nara → Osaka / Universal City may be better for JR-connected hotels."
      }
    ]
  },
  {
    "date": "Thu 12 Nov",
    "city": "Osaka",
    "title": "Universal Studios Japan",
    "base": "Osaka night 2",
    "summary": "Better logistics: wake up in Osaka, less back-and-forth, easier final airport transfer.",
    "start": "07:15",
    "items": [
      {
        "id": "d10_usj_train",
        "name": "Osaka hotel → Universal City Station",
        "time": "07:15",
        "duration": 35,
        "transit": 35,
        "walk": 0.5,
        "effort": 1,
        "cost": 3,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "Much easier than coming from Kyoto. Arrive before opening if Nintendo/Harry Potter/headliners matter.",
        "tip": "Thursday is also a good weekday choice. Staying in Osaka reduces stress significantly.",
        "transport": "From Osaka/Umeda/Namba: JR lines via Nishikujo to Universal City. From Universal City hotels: walk."
      },
      {
        "id": "d10_usj_entry",
        "name": "USJ rope drop + timed entries",
        "time": "08:00",
        "duration": 540,
        "transit": 0,
        "walk": 8.0,
        "effort": 5,
        "cost": 70,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "Full theme-park day. Prioritize Super Nintendo World timed entry, Harry Potter, Hollywood Dream, shows and seasonal events.",
        "tip": "Use the official USJ app. Consider Express Pass if Super Nintendo World/Mario Kart is essential.",
        "transport": "The park entrance is by Universal City Station. Once inside, use the USJ app for live waits and area entry timing."
      },
      {
        "id": "d10_express",
        "name": "Universal Express Pass buffer",
        "time": "Optional",
        "duration": 0,
        "transit": 0,
        "walk": 0,
        "effort": 0,
        "cost": 85,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional but useful if budget allows and you care about Nintendo/Harry Potter/headliners.",
        "tip": "Prices vary heavily by date and type, so this is a placeholder budget line.",
        "transport": "Buy only through official/authorized channels after choosing the exact date."
      },
      {
        "id": "d10_evening",
        "name": "Return to Osaka hotel / simple dinner",
        "time": "19:30",
        "duration": 45,
        "transit": 20,
        "walk": 0.6,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "Keep the evening simple. You will be tired and flying the next day.",
        "tip": "If staying near Universal City, this is effortless. If staying Namba/Umeda, trains are still much shorter than Kyoto.",
        "transport": "Universal City → Nishikujo → Osaka/Namba route depending on hotel."
      }
    ]
  },
  {
    "date": "Fri 13 Nov",
    "city": "Osaka",
    "title": "Osaka final day · Dotonbori / Umeda · KIX departure 23:10",
    "base": "Flight day",
    "summary": "Your flight leaves KIX at 23:10, so this becomes a real Osaka day before the airport.",
    "start": "10:00",
    "items": [
      {
        "id": "d11_checkout",
        "name": "Hotel checkout + luggage storage",
        "time": "10:00",
        "duration": 45,
        "transit": 0,
        "walk": 0.3,
        "effort": 1,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80",
        "desc": "Check out and leave luggage at the hotel or station lockers. Choose based on hotel area and airport route.",
        "tip": "If staying in Namba, leave luggage near Namba for easy Nankai access to KIX. If staying near Universal City, consider luggage storage at hotel and return before airport transfer.",
        "transport": "No major transport yet. Confirm hotel luggage storage before booking."
      },
      {
        "id": "d11_osaka_castle",
        "name": "Osaka Castle Park",
        "time": "11:15",
        "duration": 90,
        "transit": 30,
        "walk": 1.8,
        "effort": 2,
        "cost": 0,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1590253230532-a67f6bc61c9e?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional classic Osaka photo stop. Best as a park/exterior visit; the interior museum is not essential for this trip.",
        "tip": "Add if you want a more traditional Osaka landmark before the urban afternoon.",
        "transport": "Use JR/metro depending on hotel. From Namba: subway/JR via Morinomiya or Osakajokoen. From Umeda: JR Loop Line."
      },
      {
        "id": "d11_namba",
        "name": "Namba · Shinsaibashi · Dotonbori",
        "time": "14:00",
        "duration": 150,
        "transit": 25,
        "walk": 2.4,
        "effort": 2,
        "cost": 0,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=900&q=80",
        "desc": "The best final Osaka atmosphere: canals, neon, signs, arcades, food streets and easy last shopping.",
        "tip": "Good final-day photography and easy to keep flexible.",
        "transport": "Use metro/JR to Namba/Shinsaibashi. If your hotel is in Namba, this is the easiest final-day base."
      },
      {
        "id": "d11_umeda",
        "name": "Umeda Sky Building sunset add-on",
        "time": "17:00",
        "duration": 90,
        "transit": 25,
        "walk": 1.0,
        "effort": 1,
        "cost": 13,
        "core": false,
        "photo": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=80",
        "desc": "Optional final viewpoint before going to the airport. Good if the weather is clear.",
        "tip": "Only add if you are not worried about time. Otherwise stay around Namba and head to KIX calmly.",
        "transport": "Metro/JR to Osaka/Umeda, then walk. From there, continue to KIX by JR or return to Namba for Nankai depending on luggage."
      },
      {
        "id": "d11_kix",
        "name": "Transfer to Kansai International Airport (KIX)",
        "time": "19:45",
        "duration": 75,
        "transit": 75,
        "walk": 0.6,
        "effort": 1,
        "cost": 15,
        "core": true,
        "photo": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=80",
        "desc": "Your return flight departs KIX at 23:10. Aim to reach the airport around 20:45–21:00.",
        "tip": "Do not cut this close. Leave Osaka around 19:30–20:00 depending on hotel/luggage location.",
        "transport": "From Namba: Nankai Rapi:t or Airport Express to KIX. From Osaka/Umeda: JR airport route. From Universal City: connect via Nishikujo/Osaka or use taxi to a convenient airport train/bus point."
      }
    ]
  }
];
